### ISSUE TITLE
Fails to identify 64-bit version of Elite: Dangerous

### ISSUE THREAD

**Issue by Sunlis** [RobCubed/EliteDangerousCrosshair#2]
The most recent update brought us a 64-bit version of the game, which is a separate executable and isn't detected by EliteDangerousCrosshair. EDC shows "Game Not Found".

**Comment by RobUnderscore** [comment]
Will take a look tonight when I get home, thanks for the heads up

**Comment by RobUnderscore** [comment]
Fixed!

Check the releases section or grab the latest release here:

http://www.robertwhittemore.com/publish/EliteDangerousCrosshair/
